# Generated by Django 4.1.3 on 2022-11-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_employee_accounts_em_id_7d6d63_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employee'},
        ),
    ]
