# Generated by Django 4.1.3 on 2023-11-08 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('info', models.TextField(blank=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='accounts.employee')),
            ],
            options={
                'verbose_name_plural': 'Company',
            },
        ),
        migrations.CreateModel(
            name='CompanyAssets',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_name', models.CharField(max_length=200, null=True, verbose_name='Device Name')),
                ('device_type', models.CharField(max_length=100, null=True, verbose_name='Device Type')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_device', to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Company Assets',
            },
        ),
        migrations.CreateModel(
            name='EmployeeOfCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='accounts.employee')),
            ],
            options={
                'verbose_name_plural': 'Employee of Company List',
            },
        ),
        migrations.CreateModel(
            name='DeligateAssetstoEmployee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checking_out_date', models.DateTimeField(null=True, verbose_name='Checking Out Date')),
                ('checking_out_condition_log', models.CharField(blank=True, max_length=500, null=True, verbose_name='Checking Out Condition')),
                ('return_date', models.DateTimeField(null=True, verbose_name='Return Date')),
                ('return_condition_log', models.CharField(blank=True, max_length=500, null=True, verbose_name='Return Condition')),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_assets', to='company.companyassets')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee', to='accounts.employee')),
            ],
            options={
                'verbose_name_plural': 'Deligate Assets to Employees',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(related_name='employees', through='company.EmployeeOfCompany', to='accounts.employee'),
        ),
    ]
