# Generated by Django 4.1.3 on 2022-11-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employee_employee_accounts_em_id_7d6d63_idx'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employees',
            field=models.ManyToManyField(related_name='employees', through='company.EmployeeOfCompany', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='deligateassetstoemployee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_employee', to='accounts.employee'),
        ),
        migrations.AlterField(
            model_name='employeeofcompany',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='accounts.employee'),
        ),
    ]
