# Generated by Django 4.1.3 on 2022-11-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employee_options'),
        ('company', '0002_alter_company_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_admin', to='accounts.employee'),
        ),
    ]
